---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Loop through domains to configure Nginx
  include_tasks: setup_site.yml
  loop: "{{ nginx_domains }}"
  loop_control:
    label: "{{ item.name }} ({{ item.domain }})"
  vars:
    name: "{{ item.name }}"
    domain: "{{ item.domain }}"

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx
